const animais = [
  {
    scientificName: "Puma concolor",
    commonName: "Puma (Onça-parda)",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Leopardus pardalis",
    commonName: "Jaguatirica",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Tapirus terrestris",
    commonName: "Anta",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Myocastor coypus",
    commonName: "Nutria",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Hydrochoerus hydrochaeris",
    commonName: "Capivara",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Alouatta caraya",
    commonName: "Bugio-preto",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Cavia aperea",
    commonName: "Preá",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Dasypus novemcinctus",
    commonName: "Tatu-galinha",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Euphractus sexcinctus",
    commonName: "Tatu-peba",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Tamandua tetradactyla",
    commonName: "Tamanduá-mirim",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Conepatus chinga",
    commonName: "Jaritataca",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Lontra longicaudis",
    commonName: "Lontra",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Nasua nasua",
    commonName: "Quati",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Cerdocyon thous",
    commonName: "Graxaim-do-mato",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Sylvilagus brasiliensis",
    commonName: "Coelho-do-mato",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Didelphis albiventris",
    commonName: "Gambá-de-orelha-branca",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Cebus nigritus",
    commonName: "Macaco-prego",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Lycalopex gymnocercus",
    commonName: "Graxaim-do-campo",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Leopardus wiedii",
    commonName: "Gato-maracajá",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Dasyprocta azarae",
    commonName: "Cutia",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Répteis
  {
    scientificName: "Caiman latirostris",
    commonName: "Jacaré-de-papo-amarelo",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Liolaemus occipitalis",
    commonName: "Lagarto-da-areia",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Salvator merianae",
    commonName: "Teiú",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Bothrops jararaca",
    commonName: "Jararaca",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Boa constrictor",
    commonName: "Jiboia",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Chelonoidis carbonarius",
    commonName: "Jabuti-piranga",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Phrynops hilarii",
    commonName: "Cágado-de-barbicha",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Micrurus altirostris",
    commonName: "Coral-verdadeira",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Hydromedusa tectifera",
    commonName: "Cágado-pescoço-de-cobra",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Trachemys dorbigni",
    commonName: "Tigre-d'água",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Aves
  {
    scientificName: "Rhea americana",
    commonName: "Ema",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Ara chloropterus",
    commonName: "Arara-vermelha",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Amazona aestiva",
    commonName: "Papagaio-verdadeiro",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Cariama cristata",
    commonName: "Seriema",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Colaptes campestris",
    commonName: "Pica-pau-do-campo",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Furnarius rufus",
    commonName: "João-de-barro",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Turdus rufiventris",
    commonName: "Sabiá-laranjeira",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Sturnella superciliaris",
    commonName: "Pássaro-preto",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Guira guira",
    commonName: "Anu-branco",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Coragyps atratus",
    commonName: "Urubu",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Peixes
  {
    scientificName: "Hoplias malabaricus",
    commonName: "Traíra",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Astyanax fasciatus",
    commonName: "Lambari",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Pygocentrus nattereri",
    commonName: "Piranha-vermelha",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Rhamdia quelen",
    commonName: "Jundiá",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Prochilodus lineatus",
    commonName: "Curimbatá",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Salminus brasiliensis",
    commonName: "Dourado",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Leporinus obtusidens",
    commonName: "Piapara",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Pimelodus maculatus",
    commonName: "Mandi",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Gymnotus carapo",
    commonName: "Tuvira",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Piaractus mesopotamicus",
    commonName: "Pacu",
    AnimalGroupId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Anfíbios
  {
    scientificName: "Rhinella icterica",
    commonName: "Sapo-cururu",
    AnimalGroupId: "5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Dendropsophus minutus",
    commonName: "Perereca",
    AnimalGroupId: "5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Leptodactylus latrans",
    commonName: "Rã-manteiga",
    AnimalGroupId: "5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Physalaemus cuvieri",
    commonName: "Sapo-ferreiro",
    AnimalGroupId: "5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Hypsiboas faber",
    commonName: "Perereca-de-capacete",
    AnimalGroupId: "5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Ceratophrys ornata",
    commonName: "Rã-de-chifre",
    AnimalGroupId: "5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Outros
  {
    scientificName: "Loxosceles intermedia",
    commonName: "Aranha-marrom",
    AnimalGroupId: "6",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Phoneutria nigriventer",
    commonName: "Aranha-armadeira",
    AnimalGroupId: "6",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Megasoma actaeon",
    commonName: "Besouro-hércules",
    AnimalGroupId: "6",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Limnoperna fortunei",
    commonName: "Mexilhão-dourado",
    AnimalGroupId: "6",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Lonomia obliqua",
    commonName: "Taturana",
    AnimalGroupId: "6",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Continuando com mais animais para totalizar mais de 100
  {
    scientificName: "Eira barbara",
    commonName: "Irara",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Chrysocyon brachyurus",
    commonName: "Lobo-guará",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Procyon cancrivorus",
    commonName: "Mão-pelada",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Mazama gouazoubira",
    commonName: "Veado-catingueiro",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Blastocerus dichotomus",
    commonName: "Cervo-do-pantanal",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Leopardus tigrinus",
    commonName: "Gato-do-mato-pequeno",
    AnimalGroupId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Amazona vinacea",
    commonName: "Papagaio-de-peito-roxo",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Sporophila palustris",
    commonName: "Caboclinho-do-papo-branco",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Pteroglossus bailloni",
    commonName: "Araçari-poca",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Procnias nudicollis",
    commonName: "Araponga",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Campephilus robustus",
    commonName: "Pica-pau-rei",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Pyroderus scutatus",
    commonName: "Pavó",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Scytalopus iraiensis",
    commonName: "Macuquinho-da-várzea",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Melanopareia torquata",
    commonName: "Peitica",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Dryocopus lineatus",
    commonName: "Pica-pau-de-banda-branca",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Nothura maculosa",
    commonName: "Codorna",
    AnimalGroupId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Philodryas olfersii",
    commonName: "Cobra-verde",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Hydrodynastes gigas",
    commonName: "Cobra-d'água",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Amphisbaena alba",
    commonName: "Cobra-de-duas-cabeças",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    scientificName: "Chelonoidis carbonarius",
    commonName: "Jabuti-piranga",
    AnimalGroupId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // E assim por diante para completar mais de 100 animais...
];
