name: Lighthouse

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Iniciar servidor
        run: npm start &
        env:
          NODE_ENV: production

      - name: Instalar dependências do Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxcursor1 libxi6 libxtst6 libnss3 libxrandr2 libgbm1 libasound2

      - name: Executar Lighthouse CI
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: 'http://localhost:3000'
          chromeFlags: '--no-sandbox --disable-gpu'
