name: OWASP Dependency-Check


on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        run: npm i
      - name: Run OWASP Dependency-Check
        run: npm run owasp